name: Hosting

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        npm install && npm run build
    - name: Launch
      run: |
        sudo npm install -g firebase-tools --unsafe-perm
        firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
